[package]
name = "gl_wrapper"
version = "0.1.0"
authors = ["Petr.volf <petr.volf216@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
log = "0.4"
snailquote = "0.3.0"
thiserror = "1.0"